import { type Algorithm, hash, parseOptions, verify, type Version } from "@node-rs/argon2";

import type { PasswordHasher } from "../application/ports/password-hasher.js";

/**
 * Tuning for argon2id. Higher is stronger and slower — the cost is paid by
 * your server on every login, and by an attacker on every guess.
 *
 * The defaults below are OWASP's current minimum recommendation. They are a
 * *floor*, not a target: raise them to whatever your hardware tolerates.
 * See `docs/security/password-storage.md` for how to measure that.
 */
export interface Argon2Parameters {
  /** KiB of memory per hash. The main lever against GPU/ASIC attacks. */
  readonly memoryCost: number;
  /** Passes over memory. Raises cost without raising memory footprint. */
  readonly timeCost: number;
  /** Lanes computed in parallel. */
  readonly parallelism: number;
}

/**
 * OWASP minimum for argon2id: 19 MiB, 2 iterations, 1 lane.
 *
 * Memory is the parameter that matters most. argon2's resistance to
 * specialized cracking hardware comes from forcing each guess to allocate
 * real memory — a GPU with thousands of cores has nowhere near thousands of
 * times the memory bandwidth, so memory-hardness is what stops an attacker
 * trading silicon for speed. Raising `timeCost` alone buys far less.
 */
export const DEFAULT_ARGON2_PARAMETERS: Argon2Parameters = {
  memoryCost: 19_456,
  timeCost: 2,
  parallelism: 1,
};

/**
 * `Algorithm.Argon2id` and `Version.V0x13` as plain numbers.
 *
 * The library declares both as ambient `const enum`s, which `isolatedModules`
 * forbids referencing — a const enum is erased and inlined at compile time,
 * so it cannot exist for a transpiler compiling one file at a time. Confirmed
 * at runtime: both objects are exported as `{}`, so importing them by name
 * would have produced `undefined` rather than a value.
 *
 * They are still imported as *types* — type-only usage is erased, so
 * `isolatedModules` permits it — and the constants are cast to those types so
 * comparisons against a parsed hash stay enum-safe rather than degrading to
 * bare number comparison. See docs/guides/typescript-conventions.md.
 */
const ARGON2ID = 2 as Algorithm;
const ARGON2_VERSION_0X13 = 1 as Version;

/**
 * argon2id-backed {@link PasswordHasher}.
 *
 * ## Why argon2id
 *
 * argon2 has three variants. **argon2i** resists side-channel attacks but is
 * weaker against time-memory tradeoffs; **argon2d** is the reverse. **argon2id**
 * runs the first half in argon2i mode and the rest in argon2d mode, which
 * gets most of both. RFC 9106 names it the default choice, and it is the one
 * to pick unless you have a specific reason not to.
 *
 * ## Why not bcrypt or scrypt
 *
 * bcrypt is not broken, and it is still a defensible choice. Its limits are
 * real though: a fixed 4 MiB working set that cannot be raised, so it has not
 * become meaningfully harder to attack as hardware improved, and a 72-byte
 * input truncation that silently ignores anything longer — which turns a long
 * passphrase into a shorter one without telling anybody.
 *
 * scrypt is memory-hard and fine. argon2id is simply the newer design that
 * won the Password Hashing Competition and addressed scrypt's tradeoffs
 * directly.
 *
 * **What matters far more than the choice among these three is not using
 * anything else.** MD5, SHA-1, SHA-256, and any bare cryptographic hash are
 * wrong here regardless of salting, because they are built to be *fast* —
 * exactly the property you do not want when an attacker holds your database
 * and is making billions of guesses per second.
 */
export class Argon2PasswordHasher implements PasswordHasher {
  private readonly parameters: Argon2Parameters;
  private readonly options: {
    algorithm: Algorithm;
    version: Version;
    memoryCost: number;
    timeCost: number;
    parallelism: number;
  };

  constructor(parameters: Argon2Parameters = DEFAULT_ARGON2_PARAMETERS) {
    assertUsableParameters(parameters);

    this.parameters = parameters;
    this.options = {
      algorithm: ARGON2ID,
      version: ARGON2_VERSION_0X13,
      memoryCost: parameters.memoryCost,
      timeCost: parameters.timeCost,
      parallelism: parameters.parallelism,
    };
  }

  /**
   * The salt is generated by the library, per call, from a CSPRNG — not
   * supplied here. Salting is not optional and not a place for judgment: it
   * is what stops one precomputed table from cracking every account at once,
   * and what stops two users with the same password having the same hash.
   */
  async hash(plaintext: string): Promise<string> {
    return hash(plaintext, this.options);
  }

  async verify(plaintext: string, encodedHash: string): Promise<boolean> {
    try {
      return await verify(encodedHash, plaintext, this.options);
    } catch {
      // A malformed or unrecognized hash means authentication fails, the same
      // as a wrong password. Throwing would push callers into a catch block
      // where the easiest mistake is to treat "couldn't check" as "checked
      // and it was fine" — and any difference visible to the client would
      // reveal something about the stored credential.
      return false;
    }
  }

  /**
   * Implemented by parsing the stored hash's own parameters, because the
   * library has no `needsRehash` of its own — only `parseOptions`.
   *
   * Rehashes when the stored hash is *weaker* than current settings, not
   * merely different. The distinction matters: if someone lowers a parameter
   * (to shed load, say), "different" would trigger a mass re-hash of every
   * password down to the weaker setting on next login, quietly degrading the
   * whole system. Only upgrades should propagate.
   *
   * `parallelism` is deliberately excluded. It is a throughput knob rather
   * than a strength one, and a change in either direction does not map
   * cleanly onto stronger or weaker.
   */
  needsRehash(encodedHash: string): boolean {
    let parsed;
    try {
      parsed = parseOptions(encodedHash);
    } catch {
      // Only reachable for a malformed hash. `verify` has already returned
      // false for those by the time the login flow consults this, so a `true`
      // here would only invite a pointless write.
      return false;
    }

    return (
      parsed.algorithm !== ARGON2ID ||
      parsed.version !== ARGON2_VERSION_0X13 ||
      parsed.memoryCost < this.parameters.memoryCost ||
      parsed.timeCost < this.parameters.timeCost
    );
  }
}

function assertUsableParameters(parameters: Argon2Parameters): void {
  // Guards against a configuration mistake silently weakening every password
  // in the system. Misconfiguration is the realistic failure here, not a
  // flawed algorithm — and a hasher running at 1 MiB looks and behaves
  // exactly like one running at 19 MiB from the outside.
  if (parameters.memoryCost < 8) {
    throw new Error(
      `argon2 memoryCost must be at least 8 KiB, got ${String(parameters.memoryCost)}.`,
    );
  }
  if (parameters.timeCost < 1) {
    throw new Error(`argon2 timeCost must be at least 1, got ${String(parameters.timeCost)}.`);
  }
  if (parameters.parallelism < 1) {
    throw new Error(
      `argon2 parallelism must be at least 1, got ${String(parameters.parallelism)}.`,
    );
  }
}
